### PR TITLE
Update deb_packages.rst

### PR DESCRIPTION
**Pull request by ReifiedException**
Debian package name is alignak-all, not alignak

### CODE REVIEW

**Comment by elohmrow** [comment]
I was just about to issue the same PR.

**Comment by ddurieux** [comment]
Hello, thanks, but we had works last 2 weeks to have own repository for debian, the website and doc will be updated in couple of hours, you can see the informations before here: https://github.com/Alignak-monitoring/alignak-monitoring.github.io/pull/22/files

There are only the testing deb, for the stable the deb files will be uploaded in couple of days

**Comment by elohmrow** [comment]
Thanks @ddurieux!

**Comment by ddurieux** [comment]
So you can use the testing repository, it works.
If you have problems say us to fix it, ok? it's mainly  because I'm not using Debian system :p
Thanks ^^

**Comment by elohmrow** [comment]
hi @ddurieux - the only problem i had so far installing the dev branch here was fixed by updating my version of setuptools.

**Comment by dan-petty** [comment]
The documentation is still wrong. :(

**Comment by elohmrow** [comment]
Yes, well, I gave up on alignak, unfortunately.  This was one of the reasons.

**Comment by dan-petty** [comment]
So would you recommend using shinken?

**Comment by elohmrow** [comment]
No - I decided the configuration of a nagios-alike and the trouble with reliably automating this and the fact that shinken seems abandoned was too much.  So I moved on to munin.  I'd love to use alignak or even shinken, but they're just not ready yet, imo.

**Comment by ddurieux** [comment]
Ok so what version of setuptool you have ? (the version had the problem?)

**Comment by ddurieux** [comment]
Seems you not used the new system to install, check the page http://www.alignak.net/download/

**Comment by mohierf** [comment]
Drop this PR. No more interest for this. The wholedocumentation has been hugely refactored and the installation is now stable and well documented. Stay tuned for merge to come rapidly...

**Pull request closed without merging**
